In [2]:
#import dependencies
import pandas as pd
import requests
import json
import datetime as dt
# from config import api_key

In [3]:
#save file path into variable
csv_file = '../Resources/coin_Dogecoin.csv'

In [4]:
#read csv
doge_df = pd.read_csv(csv_file)

In [5]:
doge_df

,SNo,Name,Symbol,Date,High,Low,Open,Close,Volume,Marketcap
0,1,Dogecoin,DOGE,2013-12-16 23:59:59,0.000866,0.000150,0.000299,0.000205,0.000000e+00,1.509085e+06
1,2,Dogecoin,DOGE,2013-12-17 23:59:59,0.000289,0.000116,0.000207,0.000269,0.000000e+00,2.169688e+06
2,3,Dogecoin,DOGE,2013-12-18 23:59:59,0.000362,0.000205,0.000267,0.000362,0.000000e+00,3.188943e+06
3,4,Dogecoin,DOGE,2013-12-19 23:59:59,0.001520,0.000328,0.000395,0.001162,0.000000e+00,1.115034e+07
4,5,Dogecoin,DOGE,2013-12-20 23:59:59,0.001143,0.000662,0.001143,0.000704,0.000000e+00,7.284337e+06
...,...,...,...,...,...,...,...,...,...,...
2755,2756,Dogecoin,DOGE,2021-07-02 23:59:59,0.247997,0.238848,0.243982,0.245264,1.321471e+09,3.194925e+10
2756,2757,Dogecoin,DOGE,2021-07-03 23:59:59,0.250214,0.242454,0.245106,0.246411,9.170158e+08,3.210491e+10
2757,2758,Dogecoin,DOGE,2021-07-04 23:59:59,0.252567,0.243425,0.246425,0.246483,9.735115e+08,3.211767e+10
2758,2759,Dogecoin,DOGE,2021-07-05 23:59:59,0.246419,0.227838,0.246419,0.231614,1.267949e+09,3.018344e+10
2759,2760,Dogecoin,DOGE,2021-07-06 23:59:59,0.241910,0.229842,0.231216,0.234422,1.265920e+09,3.055252e+10

In [6]:
doge_df.drop(['Volume', 'Marketcap'], axis = 1, inplace = True)

In [7]:
doge_df

,SNo,Name,Symbol,Date,High,Low,Open,Close
0,1,Dogecoin,DOGE,2013-12-16 23:59:59,0.000866,0.000150,0.000299,0.000205
1,2,Dogecoin,DOGE,2013-12-17 23:59:59,0.000289,0.000116,0.000207,0.000269
2,3,Dogecoin,DOGE,2013-12-18 23:59:59,0.000362,0.000205,0.000267,0.000362
3,4,Dogecoin,DOGE,2013-12-19 23:59:59,0.001520,0.000328,0.000395,0.001162
4,5,Dogecoin,DOGE,2013-12-20 23:59:59,0.001143,0.000662,0.001143,0.000704
...,...,...,...,...,...,...,...,...
2755,2756,Dogecoin,DOGE,2021-07-02 23:59:59,0.247997,0.238848,0.243982,0.245264
2756,2757,Dogecoin,DOGE,2021-07-03 23:59:59,0.250214,0.242454,0.245106,0.246411
2757,2758,Dogecoin,DOGE,2021-07-04 23:59:59,0.252567,0.243425,0.246425,0.246483
2758,2759,Dogecoin,DOGE,2021-07-05 23:59:59,0.246419,0.227838,0.246419,0.231614
2759,2760,Dogecoin,DOGE,2021-07-06 23:59:59,0.241910,0.229842,0.231216,0.234422

In [9]:
doge_df['Date'] = pd.to_datetime(doge_df['Date'])

In [14]:
doge_df['Date'][0].year

2013

In [18]:
doge_df.loc[(doge_df['Date'].dt.year >= 2018) & (doge_df['Date'].dt.year <= 2021)]

,SNo,Name,Symbol,Date,High,Low,Open,Close
1477,1478,Dogecoin,DOGE,2018-01-01 23:59:59,0.009063,0.008101,0.009031,0.008909
1478,1479,Dogecoin,DOGE,2018-01-02 23:59:59,0.009598,0.008551,0.008873,0.009145
1479,1480,Dogecoin,DOGE,2018-01-03 23:59:59,0.009584,0.008882,0.009088,0.009320
1480,1481,Dogecoin,DOGE,2018-01-04 23:59:59,0.010036,0.008768,0.009346,0.009644
1481,1482,Dogecoin,DOGE,2018-01-05 23:59:59,0.012283,0.009589,0.009660,0.012167
...,...,...,...,...,...,...,...,...
2755,2756,Dogecoin,DOGE,2021-07-02 23:59:59,0.247997,0.238848,0.243982,0.245264
2756,2757,Dogecoin,DOGE,2021-07-03 23:59:59,0.250214,0.242454,0.245106,0.246411
2757,2758,Dogecoin,DOGE,2021-07-04 23:59:59,0.252567,0.243425,0.246425,0.246483
2758,2759,Dogecoin,DOGE,2021-07-05 23:59:59,0.246419,0.227838,0.246419,0.231614
2759,2760,Dogecoin,DOGE,2021-07-06 23:59:59,0.241910,0.229842,0.231216,0.234422