In [1]:
#import dependencies
import pandas as pd
import datetime as dt

In [2]:
#save file path into variable
csv_file = '../Resources/coin_Binance_yahoo.csv'

In [3]:
#read csv
binance_df = pd.read_csv(csv_file)

In [4]:
binance_df.drop('Adj Close', axis = 1, inplace = True)

In [5]:
binance_df['Date'] = pd.to_datetime(binance_df['Date'])

In [6]:
binance_df

           Date        Open        High         Low       Close        Volume
0    2018-01-01    8.629530    8.700570    7.959220    8.414610  6.642280e+07
1    2018-01-02    8.457700    9.122590    8.217180    8.837770  1.047890e+08
2    2018-01-03    8.770140    9.580780    8.529180    9.535880  1.088520e+08
3    2018-01-04    9.445840    9.538490    8.854130    9.213990  1.588190e+08
4    2018-01-05    9.145680   16.717699    9.094680   14.917200  3.415050e+08
...         ...         ...         ...         ...         ...           ...
1436 2021-12-07  589.110779  593.799255  573.338501  579.689880  2.112955e+09
1437 2021-12-08  579.182678  607.780884  567.616211  607.592773  2.245502e+09
1438 2021-12-09  606.635925  616.647339  568.039551  571.648987  2.132955e+09
1439 2021-12-10  570.981018  594.597229  551.735840  552.966858  2.089946e+09
1440 2021-12-11  554.689026  571.479309  543.855896  563.557251  2.061808e+09

[1441 rows x 6 columns]

In [7]:
filtered_binance_df = binance_df.loc[(binance_df['Date'].dt.year >= 2018) & (binance_df['Date'].dt.year <= 2021)]

In [8]:
filtered_binance_df.set_index('Date', inplace = True)

In [9]:
grouped_filtered_binance_df = filtered_binance_df.groupby([filtered_binance_df.index.year, filtered_binance_df.index.month])

In [10]:
grouped_filtered_binance_df.count()

           Open  High  Low  Close  Volume
Date Date
2018 1       31    31   31     31      31
     2       28    28   28     28      28
     3       31    31   31     31      31
     4       30    30   30     30      30
     5       31    31   31     31      31
     6       30    30   30     30      30
     7       31    31   31     31      31
     8       31    31   31     31      31
     9       30    30   30     30      30
     10      31    31   31     31      31
     11      30    30   30     30      30
     12      31    31   31     31      31
2019 1       31    31   31     31      31
     2       28    28   28     28      28
     3       31    31   31     31      31
     4       30    30   30     30      30
     5       31    31   31     31      31
     6       30    30   30     30      30
     7       31    31   31     31      31
     8       31    31   31     31      31
     9       30    30   30     30      30
     10      31    31   31     31      31
     11      30    30   30     30      30
     12      31    31   31     31      31
2020 1       31    31   31     31      31
     2       29    29   29     29      29
     3       31    31   31     31      31
     4       29    29   29     29      29
     5       31    31   31     31      31
     6       30    30   30     30      30
     7       31    31   31     31      31
     8       31    31   31     31      31
     9       30    30   30     30      30
     10      28    28   28     28      28
     11      30    30   30     30      30
     12      31    31   31     31      31
2021 1       31    31   31     31      31
     2       28    28   28     28      28
     3       31    31   31     31      31
     4       30    30   30     30      30
     5       31    31   31     31      31
     6       30    30   30     30      30
     7       31    31   31     31      31
     8       31    31   31     31      31
     9       30    30   30     30      30
     10      31    31   31     31      31
     11      30    30   30     30      30
     12      11    11   11     11      11

In [11]:
final_df_data = []

In [12]:
final_df_data.append(grouped_filtered_binance_df['High'].max())

final_df_data.append(grouped_filtered_binance_df['Low'].min())

final_df_data.append(grouped_filtered_binance_df['Open'].mean())

final_df_data.append(grouped_filtered_binance_df['Close'].mean())

final_df_data.append(grouped_filtered_binance_df['High'].max() * grouped_filtered_binance_df['Volume'].max())

In [13]:
final_df = pd.DataFrame(final_df_data)

In [14]:
final_df = final_df.transpose()

In [15]:
final_df.rename(columns={'Unnamed 0': 'Marketcap'}, inplace = True)

In [16]:
final_df.index = final_df.index.map('{0[0]}0{0[1]}'.format)

In [17]:
final_df.index = final_df.index.astype(int)

In [18]:
final_df = final_df.copy().loc[final_df.index <= 202105]

In [19]:
final_df['Symbol'] = 'BNB'
final_df['Name'] = 'Binance Coin'
final_df.reset_index(inplace = True)
final_df.rename(columns={'index': 'Date'}, inplace = True)
final_df

,Date,High,Low,Open,Close,Marketcap,Symbol,Name
0,201801,24.912100,7.959220,15.020729,15.064079,1.586953e+10,BNB,Binance Coin
1,201802,11.870700,5.590070,9.611275,9.586875,1.293455e+09,BNB,Binance Coin
2,201803,14.838700,7.174230,9.941918,9.944702,3.789181e+09,BNB,Binance Coin
3,201804,15.925900,10.378300,12.929007,13.020723,2.637313e+09,BNB,Binance Coin
4,201805,16.220501,11.703100,13.494781,13.489377,3.945815e+09,BNB,Binance Coin
5,201806,17.438101,13.544400,15.317423,15.315920,2.751837e+09,BNB,Binance Coin
6,201807,14.869400,11.648400,13.261926,13.220777,1.189179e+09,BNB,Binance Coin
7,201808,14.455100,8.662660,11.421727,11.339599,1.018352e+09,BNB,Binance Coin
8,201809,11.542300,9.037310,10.097378,10.052869,4.066145e+08,BNB,Binance Coin
9,201901,7.246770,5.493421,6.322238,6.321450,5.973310e+08,BNB,Binance Coin
10,201902,11.323774,6.172295,8.955847,9.101428,1.653764e+09,BNB,Binance Coin
11,201903,17.568340,10.325634,14.819533,15.060067,5.526195e+09,BNB,Binance Coin
12,201904,25.533409,16.589216,20.544795,20.703582,1.015416e+10,BNB,Binance Coin
13,201905,35.504501,18.467089,26.637544,26.985650,2.635794e+10,BNB,Binance Coin
14,201906,39.566536,29.183624,33.861130,33.848594,2.919417e+10,BNB,Binance Coin
15,201907,34.313126,24.903645,30.288731,30.122802,2.442737e+10,BNB,Binance Coin
16,201908,31.301611,21.190308,27.544658,27.334428,1.265772e+10,BNB,Binance Coin
17,201909,23.535213,14.841279,20.368949,20.186121,8.694868e+09,BNB,Binance Coin
18,202001,18.840961,12.989974,16.142879,16.287440,7.174763e+09,BNB,Binance Coin
19,202002,27.117456,17.824158,21.886327,21.925773,1.979966e+10,BNB,Binance Coin
20,202003,21.701672,6.963391,14.311835,14.085149,1.478195e+10,BNB,Binance Coin
21,202004,18.129528,12.057843,15.027594,15.181463,9.342719e+09,BNB,Binance Coin
22,202005,18.108484,14.284380,16.612723,16.612913,8.211094e+09,BNB,Binance Coin
23,202006,18.156345,15.020651,16.625572,16.570955,6.235705e+09,BNB,Binance Coin
24,202007,20.838476,15.245029,17.642364,17.812053,6.780567e+09,BNB,Binance Coin
25,202008,23.914165,19.972687,22.454535,22.530665,8.546589e+09,BNB,Binance Coin
26,202009,33.487820,18.183708,25.307139,25.504717,3.833144e+10,BNB,Binance Coin
27,202101,47.098103,35.170883,41.530250,41.749991,4.195163e+10,BNB,Binance Coin
28,202102,342.879608,43.524193,151.807812,157.668050,6.165985e+12,BNB,Binance Coin
29,202103,316.486542,209.951309,257.716138,260.716174,2.745922e+12,BNB,Binance Coin
30,202104,637.442322,301.588654,478.565206,489.268384,9.202319e+12,BNB,Binance Coin
31,202105,690.931946,213.516464,503.144575,494.574970,6.066344e+12,BNB,Binance Coin

In [20]:
final_df.to_csv('coin_Binance_yahoo_cleaned.csv', index=False)