In [1]:
#import dependencies
import pandas as pd
import datetime as dt

In [2]:
#save file path into variable
csv_file = '../Resources/coin_Binance_yahoo.csv'

In [3]:
#read csv
binance_df = pd.read_csv(csv_file)

In [4]:
binance_df.drop('Adj Close', axis = 1, inplace = True)

In [5]:
binance_df['Date'] = pd.to_datetime(binance_df['Date'])

In [6]:
binance_df

           Date        Open        High         Low       Close        Volume
0    2018-01-01    8.629530    8.700570    7.959220    8.414610  6.642280e+07
1    2018-01-02    8.457700    9.122590    8.217180    8.837770  1.047890e+08
2    2018-01-03    8.770140    9.580780    8.529180    9.535880  1.088520e+08
3    2018-01-04    9.445840    9.538490    8.854130    9.213990  1.588190e+08
4    2018-01-05    9.145680   16.717699    9.094680   14.917200  3.415050e+08
...         ...         ...         ...         ...         ...           ...
1436 2021-12-07  589.110779  593.799255  573.338501  579.689880  2.112955e+09
1437 2021-12-08  579.182678  607.780884  567.616211  607.592773  2.245502e+09
1438 2021-12-09  606.635925  616.647339  568.039551  571.648987  2.132955e+09
1439 2021-12-10  570.981018  594.597229  551.735840  552.966858  2.089946e+09
1440 2021-12-11  554.689026  571.479309  543.855896  563.557251  2.061808e+09

[1441 rows x 6 columns]

In [7]:
filtered_binance_df = binance_df.loc[(binance_df['Date'].dt.year >= 2018) & (binance_df['Date'].dt.year <= 2021)]

In [8]:
filtered_binance_df.set_index('Date', inplace = True)

In [9]:
grouped_filtered_binance_df = filtered_binance_df.groupby([filtered_binance_df.index.year, filtered_binance_df.index.month])

In [10]:
grouped_filtered_binance_df.count()

           Open  High  Low  Close  Volume
Date Date
2018 1       31    31   31     31      31
     2       28    28   28     28      28
     3       31    31   31     31      31
     4       30    30   30     30      30
     5       31    31   31     31      31
     6       30    30   30     30      30
     7       31    31   31     31      31
     8       31    31   31     31      31
     9       30    30   30     30      30
     10      31    31   31     31      31
     11      30    30   30     30      30
     12      31    31   31     31      31
2019 1       31    31   31     31      31
     2       28    28   28     28      28
     3       31    31   31     31      31
     4       30    30   30     30      30
     5       31    31   31     31      31
     6       30    30   30     30      30
     7       31    31   31     31      31
     8       31    31   31     31      31
     9       30    30   30     30      30
     10      31    31   31     31      31
     11      30    30   30     30      30
     12      31    31   31     31      31
2020 1       31    31   31     31      31
     2       29    29   29     29      29
     3       31    31   31     31      31
     4       29    29   29     29      29
     5       31    31   31     31      31
     6       30    30   30     30      30
     7       31    31   31     31      31
     8       31    31   31     31      31
     9       30    30   30     30      30
     10      28    28   28     28      28
     11      30    30   30     30      30
     12      31    31   31     31      31
2021 1       31    31   31     31      31
     2       28    28   28     28      28
     3       31    31   31     31      31
     4       30    30   30     30      30
     5       31    31   31     31      31
     6       30    30   30     30      30
     7       31    31   31     31      31
     8       31    31   31     31      31
     9       30    30   30     30      30
     10      31    31   31     31      31
     11      30    30   30     30      30
     12      11    11   11     11      11

In [11]:
final_df_data = []

In [12]:
final_df_data.append(round(grouped_filtered_binance_df['High'].max(), 3))

final_df_data.append(round(grouped_filtered_binance_df['Low'].min(), 3))

final_df_data.append(round(grouped_filtered_binance_df['Open'].mean(), 3))

final_df_data.append(round(grouped_filtered_binance_df['Close'].mean(), 3))

final_df_data.append(round(grouped_filtered_binance_df['High'].max() * grouped_filtered_binance_df['Volume'].max(), 3))

In [13]:
final_df = pd.DataFrame(final_df_data)

In [14]:
final_df = final_df.transpose()

In [15]:
final_df.rename(columns={'Unnamed 0': 'Marketcap'}, inplace = True)

In [16]:
final_df.index = final_df.index.map('{0[0]}0{0[1]}'.format)

In [17]:
final_df.index = final_df.index.astype(int)

In [18]:
final_df = final_df.copy().loc[final_df.index <= 202105]

In [19]:
final_df['Symbol'] = 'BNB'
final_df['Name'] = 'Binance Coin'
final_df.reset_index(inplace = True)
final_df.rename(columns={'index': 'Date'}, inplace = True)
final_df

,Date,High,Low,Open,Close,Marketcap,Symbol,Name
0,201801,24.912,7.959,15.021,15.064,1.586953e+10,BNB,Binance Coin
1,201802,11.871,5.590,9.611,9.587,1.293455e+09,BNB,Binance Coin
2,201803,14.839,7.174,9.942,9.945,3.789181e+09,BNB,Binance Coin
3,201804,15.926,10.378,12.929,13.021,2.637313e+09,BNB,Binance Coin
4,201805,16.221,11.703,13.495,13.489,3.945815e+09,BNB,Binance Coin
5,201806,17.438,13.544,15.317,15.316,2.751837e+09,BNB,Binance Coin
6,201807,14.869,11.648,13.262,13.221,1.189179e+09,BNB,Binance Coin
7,201808,14.455,8.663,11.422,11.340,1.018352e+09,BNB,Binance Coin
8,201809,11.542,9.037,10.097,10.053,4.066145e+08,BNB,Binance Coin
9,201901,7.247,5.493,6.322,6.321,5.973310e+08,BNB,Binance Coin
10,201902,11.324,6.172,8.956,9.101,1.653764e+09,BNB,Binance Coin
11,201903,17.568,10.326,14.820,15.060,5.526195e+09,BNB,Binance Coin
12,201904,25.533,16.589,20.545,20.704,1.015416e+10,BNB,Binance Coin
13,201905,35.505,18.467,26.638,26.986,2.635794e+10,BNB,Binance Coin
14,201906,39.567,29.184,33.861,33.849,2.919417e+10,BNB,Binance Coin
15,201907,34.313,24.904,30.289,30.123,2.442737e+10,BNB,Binance Coin
16,201908,31.302,21.190,27.545,27.334,1.265772e+10,BNB,Binance Coin
17,201909,23.535,14.841,20.369,20.186,8.694868e+09,BNB,Binance Coin
18,202001,18.841,12.990,16.143,16.287,7.174763e+09,BNB,Binance Coin
19,202002,27.117,17.824,21.886,21.926,1.979966e+10,BNB,Binance Coin
20,202003,21.702,6.963,14.312,14.085,1.478195e+10,BNB,Binance Coin
21,202004,18.130,12.058,15.028,15.181,9.342719e+09,BNB,Binance Coin
22,202005,18.108,14.284,16.613,16.613,8.211094e+09,BNB,Binance Coin
23,202006,18.156,15.021,16.626,16.571,6.235705e+09,BNB,Binance Coin
24,202007,20.838,15.245,17.642,17.812,6.780567e+09,BNB,Binance Coin
25,202008,23.914,19.973,22.455,22.531,8.546589e+09,BNB,Binance Coin
26,202009,33.488,18.184,25.307,25.505,3.833144e+10,BNB,Binance Coin
27,202101,47.098,35.171,41.530,41.750,4.195163e+10,BNB,Binance Coin
28,202102,342.880,43.524,151.808,157.668,6.165985e+12,BNB,Binance Coin
29,202103,316.487,209.951,257.716,260.716,2.745922e+12,BNB,Binance Coin
30,202104,637.442,301.589,478.565,489.268,9.202319e+12,BNB,Binance Coin
31,202105,690.932,213.516,503.145,494.575,6.066344e+12,BNB,Binance Coin

In [20]:
final_df.to_csv('coin_Binance_yahoo_cleaned.csv', index=False)